### ISSUE TITLE
Issues in Conversion Host wizard

### ISSUE THREAD

**Issue by mzazrivec** [ManageIQ/manageiq-v2v#1089] opened 2020-01-14 15:38 UTC
There's couple of issues I witnessed in conversion host wizard:

1. launch the conv. host wizard
2. select RHV
3. in next step, select a host
4. go back to initial step and select openstack this time
5. hit next
6. see the following error:

```
react-dom.development.js:11365 Uncaught TypeError: Cannot read property 'vms' of undefined
    at ConversionHostWizardHostsStep (ConversionHostWizardHostsStep.js:24)
    at renderWithHooks (react-dom.development.js:15108)
    at mountIndeterminateComponent (react-dom.development.js:17342)
    at beginWork$1 (react-dom.development.js:18486)
    at HTMLUnknownElement.callCallback (react-dom.development.js:347)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:397)
    at invokeGuardedCallback (react-dom.development.js:454)
    at beginWork$$1 (react-dom.development.js:23217)
    at performUnitOfWork (react-dom.development.js:22208)
    at workLoopSync (react-dom.development.js:22185)
```

**Comment by mzazrivec** [comment] 2020-01-14 15:38
The following error occurs on my end when I select OpenStack initially and reach the authentication tab (happens on master too):
```
miq_debug.self-1351f771c2cd2fab0d83069fd3f62aadbb7effc11a01ed4942f52308793453be.js?body=1:30 The above error occurred in the <Modal> component:
    in Modal (created by Modal)
    in Modal (created by Wizard)
    in Wizard (created by ConversionHostWizard)
    in ConversionHostWizard (created by ConnectFunction)
    in ConnectFunction (created by ConversionHostsSettings)
    in Spinner (created by ConversionHostsSettings)
    in ConversionHostsSettings (created by ConnectFunction)
    in ConnectFunction (created by Settings)
    in div (created by TabPane)
    in Transition (created by Fade)
    in Fade (created by TabPane)
    in TabPane (created by Tab)
    in Tab (created by Settings)
    in div (created by TabContent)
    in TabContent (created by Tabs)
    in div (created by Tabs)
    in TabContainer (created by Tabs)
    in Tabs (created by Uncontrolled(Tabs))
    in Uncontrolled(Tabs) (created by ForwardRef)
    in ForwardRef (created by Settings)
    in div (created by Settings)
    in Settings (created by ConnectFunction)
    in ConnectFunction (created by I18nProviderWrapper(Connect(Settings)))
    in IntlProvider (created by I18nProviderWrapper(Connect(Settings)))
    in I18nProviderWrapper(Connect(Settings)) (created by Route)
    in Route (created by Routes)
    in Routes (created by App)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by ConnectFunction)
    in ConnectFunction (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at http://localhost:3000/packs/vendor-fa9bda05266affa03459.js:416322:28
    at checkForNestedUpdates (http://localhost:3000/packs/vendor-fa9bda05266affa03459.js:416325:7)
    at scheduleUpdateOnFiber (http://localhost:3000/packs/vendor-fa9bda05266affa03459.js:414596:3)
    at Object.enqueueSetState (http://localhost:3000/packs/vendor-fa9bda05266affa03459.js:406307:5)
    at Modal.push../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:3000/packs/vendor-fa9bda05266affa03459.js:433724:16)
    at Modal.UNSAFE_componentWillReceiveProps (http://localhost:3000/packs/vendor-fa9bda05266affa03459.js:389721:12)
    at callComponentWillReceiveProps (http://localhost:3000/packs/vendor-fa9bda05266affa03459.js:406598:14)
    at updateClassInstance (http://localhost:3000/packs/vendor-fa9bda05266affa03459.js:406805:7)
    at updateClassComponent (http://localhost:3000/packs/vendor-fa9bda05266affa03459.js:410199:20)
    at beginWork$1 (http://localhost:3000/packs/vendor-fa9bda05266affa03459.js:411712:16)
(anonymous) @ react-dom.development.js:23115
checkForNestedUpdates @ react-dom.development.js:23118
scheduleUpdateOnFiber @ react-dom.development.js:21389
enqueueSetState @ react-dom.development.js:13100
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:325
UNSAFE_componentWillReceiveProps @ Modal.js:216
callComponentWillReceiveProps @ react-dom.development.js:13391
updateClassInstance @ react-dom.development.js:13598
updateClassComponent @ react-dom.development.js:16992
beginWork$1 @ react-dom.development.js:18505
beginWork$$1 @ react-dom.development.js:23193
performUnitOfWork @ react-dom.development.js:22208
workLoopSync @ react-dom.development.js:22185
renderRoot @ react-dom.development.js:21878
runRootCallback @ react-dom.development.js:21554
(anonymous) @ react-dom.development.js:11353
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
flushSyncCallbackQueueImpl @ react-dom.development.js:11349
flushSyncCallbackQueue @ react-dom.development.js:11338
discreteUpdates$1 @ react-dom.development.js:21677
discreteUpdates @ react-dom.development.js:2359
dispatchDiscreteEvent @ react-dom.development.js:5979
```

**Comment by mzazrivec** [comment] 2020-01-14 15:39
The following error shows on auth tab when I initially select RHV:
```
Warning: The prop `disableClick` of `Dropzone` is deprecated. Use onClick={evt => evt.preventDefault()} instead. This prop will be removed in the next major version. 
    in TextFileInput (created by FormField)
    in FormField (created by ConnectedField)
    in ConnectedField (created by ConnectFunction)
    in ConnectFunction (created by Connect(ConnectedField))
    in Connect(ConnectedField) (created by Field)
    in Field (created by Context.Consumer)
    in Context.Consumer (created by Hoc)
    in Hoc (created by Field)
    in Field (created by TextFileField)
    in TextFileField (created by ConversionHostWizardAuthenticationStep)
    in ConversionHostWizardAuthenticationStep (created by Form(ConversionHostWizardAuthenticationStep))
    in Form(ConversionHostWizardAuthenticationStep) (created by ConnectFunction)
    in ConnectFunction (created by Connect(Form(ConversionHostWizardAuthenticationStep)))
    in Connect(Form(ConversionHostWizardAuthenticationStep)) (created by ReduxForm)
    in ReduxForm (created by Context.Consumer)
    in Context.Consumer (created by Hoc)
    in Hoc (created by ReduxForm)
    in ReduxForm (created by ConnectFunction)
    in ConnectFunction (created by ModalWizardBody)
    in ModalWizardBody (created by ConversionHostWizardBody)
    in ConversionHostWizardBody (created by ConversionHostWizard)
    in ConversionHostWizard (created by ConnectFunction)
    in ConnectFunction (created by ConversionHostsSettings)
    in ConversionHostsSettings (created by ConnectFunction)
    in ConnectFunction (created by Settings)
    in Settings (created by ConnectFunction)
    in ConnectFunction (created by I18nProviderWrapper(Connect(Settings)))
    in I18nProviderWrapper(Connect(Settings)) (created by Route)
    in Route (created by Routes)
    in Routes (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction
```

**Comment by mturley** [comment] 2020-01-14 16:09
As I mentioned in the PR, I wasn't able to reproduce your first error here (`Cannot read property 'vms' of undefined`). @mzazrivec at some point soon when we both have time, maybe we can meet and walk through it together, I'm probably missing something (or maybe something different in the database is preventing me from seeing it).

**Comment by mturley** [comment] 2020-01-20 17:22
This is causing https://github.com/ManageIQ/manageiq-v2v/issues/1093, both issues should be closed when this is resolved.

**Comment by mzazrivec** [comment] 2020-02-04 14:03
@mturley The first and the third problem will go away with update of `react-dropzone` https://github.com/ManageIQ/manageiq-v2v/pull/1102

**Comment by mzazrivec** [comment] 2020-02-05 16:56
@mturley The second problem (the one when I select OpenStack) will go away when I do this change:
```patch
diff --git a/app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js b/app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
index c6e0e249..0cac40f8 100644
--- a/app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
+++ b/app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
@@ -87,7 +87,7 @@ export const ConversionHostWizardAuthenticationStep = ({
             component={FormField}
             controlId="verify-openstack-certs"
             style={{ marginTop: 25 }}
-            validate={() => undefined} // Force redux-form to re-run validation when this field changes, since it can unmount openstackCaCerts
+            // validate={() => undefined} // Force redux-form to re-run validation when this field changes, since it can unmount openstackCaCerts
           >
             {({ input: { value, onChange } }) => (
               <Switch

```

Right now, I'm not entirely sure how to fix this nicely 🤷

**Comment by himdel** [comment] 2020-02-06 16:15
Looks like this is the setState loop it's complaining about..

```
partialState = {labelWidth: "auto", handleWidth: "auto", value: false}, callback = ƒ ()
from Switch componentWillReceiveProps

partialState = {skipAnimation: false, offset: 0}, callback = undefined
from Switch updateContainerPosition

partialState = {handleWidth: 32, labelWidth: 32}, callback = ƒ ()
from Switch recalculateWidth

partialState = {exited: false}, callback = undefined
from Modal.prototype.UNSAFE_componentWillReceiveProps

(goto 0)
```

those 4 keep looping in order, so current theory - it's the Switch.

Without the `validate` prop..... TODO

**Comment by mturley** [comment] 2020-02-06 20:19
Oops, didn't realize #1102 had magic text to close this, reopening.

**Comment by mturley** [comment] 2020-02-06 20:21
Digging into this now.. that `validate` prop was a kludge anyway, there's probably a better way to solve the underlying issue.

**Comment by mturley** [comment] 2020-02-07 00:13
Ok @mzazrivec I think I have a solution here, but I'm not sure if it's ideal...

This must have broken when we moved from redux-form 7.2.3 to 8.2.6: https://github.com/ManageIQ/manageiq-v2v/commit/cd62e7f8c31137a1ce7a4170831386a8c3c653a3#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R77

I haven't figured out why using a `validate` function on the Field around the Switch now causes the render loop, and unfortunately removing it brings back the bug we fixed by adding it in https://github.com/ManageIQ/manageiq-v2v/pull/961. But, I found a less problematic workaround for it.

In short, the problem comes down to a bug in redux-form that apparently is still there in v8: if a field is included in the validation errors, and then unregistered (it's required, left blank, then unmounted) validation doesn't re-run, so it still fails even if everything else in the form is fine. So we just need to force validation to re-run after a field is unmounted.

I found a different way to force the form validation to re-run on every field change. We can remove this `validate` prop, and instead use `shouldError: () => true` in the `reduxForm(...)` options. The docs for this aren't great, but it runs on a field change to determine if it's necessary to check for validation errors again (defaults to [a deepEqual comparison of values](https://github.com/redux-form/redux-form/blob/master/src/defaultShouldError.js#L15)). Also I checked, and it was already around in redux-form 7.2.3, so this fix should also work if we end up needing to backport this change.

Speaking of which, the fact that we have different sets of dependency versions on ivanchuk and master now sounds like it could become a nightmare...

Anyway, this should do it:

```diff
--- a/app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
+++ b/app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
@@ -87,7 +87,6 @@ export const ConversionHostWizardAuthenticationStep = ({
             component={FormField}
             controlId="verify-openstack-certs"
             style={{ marginTop: 25 }}
-            validate={() => undefined} // Force redux-form to re-run validation when this field changes, since it can unmount openstackCaCerts
           >
             {({ input: { value, onChange } }) => (
               <Switch
@@ -126,6 +125,7 @@ export default reduxForm({
   form: stepIDs.authenticationStep,
   destroyOnUnmount: false,
   forceUnregisterOnUnmount: true,
+  shouldError: () => true, // Force validation to re-run on every field change so unmounted fields get excluded
   initialValues: {
     openstackUser: 'cloud-user',
     conversionHostSshKey: { filename: '', body: '' },
```

I'll open a PR.

**Comment by mturley** [comment] 2020-02-07 00:22
I'm definitely open to more elegant solutions, but here's the best I've got at 7pm on a Thursday: https://github.com/ManageIQ/manageiq-v2v/pull/1103

**Closed** 2020-02-07 14:47 UTC
Labels: UI, bug, bugzilla needed, v1.3
