### ISSUE TITLE
[Infra Mappings] Provide detailed info regarding why clusters/datastores/networks are missing

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/manageiq-v2v#754] opened 2018-10-30 20:30 UTC
(Edit: this is part of https://github.com/ManageIQ/manageiq-v2v/issues/766)

https://bugzilla.redhat.com/show_bug.cgi?id=1644443
https://bugzilla.redhat.com/show_bug.cgi?id=1666840

There are at least two scenarios that can cause the Infra Mapping list items to look like the following

<img width="1196" alt="screen shot 2018-10-30 at 4 25 21 pm" src="https://user-images.githubusercontent.com/15141412/47748209-9fc10b80-dc60-11e8-9ebe-3d6e2ddf428a.png">

1. A provider was removed via `Compute -> Infrastructure -> Providers`
2. A cluster was removed via `Compute -> Infrastructure -> Clusters`

We would like to provide more detailed information regarding why the clusters/networks/datastores were unable to be retrieved.

# Notes
- A `TransformationMapping` has an array of `transformation_mapping_items`.  One of these is always a mapping between some sort of source and destination compute object.  e.g.,

    ```js
    // TransformationMappingItem
    {
      source_id: "3",
      source_type: "EmsCluster",
      destination_id: "2",
      destination_type: "EmsCluster",
      transformation_mapping_id: "2",
      options: {},
      created_at: "2018-10-04T15:12:18Z",
      updated_at: "2018-10-04T15:12:18Z"
    }
    ```
- In order to display, say the mapping associated with the `TransformationMappingItem` above, we query for all `ems_clusters` (with their `storages` and `lans`), and using the `source_id` and `destination_id` of the mapping item, identify the records that we need.
- If a `Provider` is removed and re-added, its clusters' ids change, so when we try to filter 
 `ems_clusters` according to the mapping we want to display, the cluster(s) seem to be missing, so we display an error in the UI
    <img width="1260" alt="screen shot 2018-10-31 at 4 08 25 pm" src="https://user-images.githubusercontent.com/15141412/47815626-3e17a480-dd27-11e8-9466-b95beb4a0be2.png">
- In the current implementation, if any cluster(s) are missing, without any further processing, we default to saying that all other resources are missing as well (networks/datastores)
- The above scenario also occurs if a mapping's cluster is removed from the db

**Comment by michaelkro** [comment] 2018-10-30 20:30
@vconzola how would you like to handle displaying the error message?

**Comment by michaelkro** [comment] 2018-10-31 20:13
@djberg96 @jameswnl

I've added some notes to the issue description.  Please let me know if I can answer any questions or provide any additional info!

**Comment by michaelkro** [comment] 2019-01-17 20:03
![](https://github.trello.services/images/mini-trello-icon.png) [SPIKE - TransformationMapping model validation](https://trello.com/c/w3NMX2zH/218-spike-transformationmapping-model-validation)

**Comment by mturley** [comment] 2019-02-11 16:58
@vconzola we should design a more meaningful error message to add to the "Clusters/datastores/networks missing", and figure out how it should be shown (popover when you click one of those error icons, perhaps?)

Marco's suggestion from the `Infrastructure Mapping rebuild` email thread:

> "An error has been detected with your current infrastructure mapping.  This is usually caused by a change in your provider configuration.   Please note that changes to existing providers might brake your infrastructure mapping forcing you to create them again."   I am sure this can be phrase much nicer than this by somebody speaking better english than me  :-)

**Comment by vconzola** [comment] 2019-02-15 17:27
@mturley Yes, let's add a popover on the error icon(s) that says, "Infrastructure mapping errors are usually caused by a change in your provider configuration. If the source or target provider has changed you will need to delete this mapping and create a new one."

**Comment by mturley** [comment] 2019-02-27 14:37
@vconzola this is the one Brett was referring to in the `IMS 1.2 UI work` email chain yesterday under "P1 - detect provider changes". It should be straightforward.

**Comment by vconzola** [comment] 2019-02-27 15:03
@mturley Let's implement the popover on the error icon using the text I provided above. But I still think we need a better/more comprehensive long term solution.

**Comment by mturley** [comment] 2019-02-27 15:23
Ok, when we get to adding the popover, I'll reference this issue, but we can leave it open to track the longer term solution.

**Comment by mturley** [comment] 2019-03-07 15:33
Note, the longer term solution I indicated above is tracked in this BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1666840

When the backend support is complete for this mapping validation, we'll need to come back to this on the UI side to display the new error messaging.

**Comment by vconzola** [comment] 2019-03-07 21:09
@mturley Here's the mockup you requested. The same tooltip can appear when the user clicks on any of the error icons. If possible, if the error is with a mapping that can be edited (no associated plans) the edit button should be disabled too. But if this is a lot of work, don't bother with that for now. 
![infrastructure mappings w missing providers](https://user-images.githubusercontent.com/22823035/53989071-18464600-40f3-11e9-9525-ab71c299f5d1.png)

**Comment by mturley** [comment] 2019-03-07 21:10
Perfect, thanks @vconzola. I think we already disabled editing these broken mappings, since doing so would crash the mapping wizard.

**Comment by vconzola** [comment] 2019-03-07 21:11
OK, great.

**Comment by mturley** [comment] 2019-12-03 23:52
This falls under the same "should we do this in the backend at all" umbrella as https://github.com/ManageIQ/manageiq-v2v/issues/878 and https://github.com/ManageIQ/manageiq-v2v/issues/877.

**Comment by mturley** [comment] 2019-12-04 19:04
Closing this, if we end up implementing it we can cover it in https://github.com/ManageIQ/manageiq-v2v/issues/877.

**Closed by mturley** 2019-12-04 19:04 UTC
Labels: UI, future, needs-api, needs-design
