### ISSUE TITLE
Overlay using componentWillReceiveProps

### ISSUE THREAD

**Issue by himdel** [ManageIQ/manageiq-v2v#1037] opened 2019-09-25 13:58 UTC
When opening `/migration#/plans`

```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Overlay
```

Cc @mturley , @Hyperkid123

**Comment by mturley** [comment] 2019-09-25 18:35
Hmm, I wonder how we can fix this, since Overlay is a component we import from `patternfly-react`, which imports it from `react-bootstrap`. react-bootstrap stopped supporting bootstrap v3, so they are not actively releasing fixes for that branch. I found an issue for this on their end that has been open for 22 days: https://github.com/react-bootstrap/react-bootstrap/issues/4398

I posted a comment on that issue to see if they have any intent to release a fix, but if they don't we'll need to copy those components in-house in patternfly-react and fix them there. I opened an issue in patternfly-react to track it: https://github.com/patternfly/patternfly-react/issues/3010

**Comment by mturley** [comment] 2019-09-25 18:56
Looks like there is some activity on that react-bootstrap issue, so I'll keep an eye on it and see if that release goes out any time soon.

**Comment by himdel** [comment] 2019-09-25 19:12
Ooh, I missed the "comes from patternfly" bit :). Thanks for following up!

We can probably replace it with our own implementation if worst comes to worst :).

**Comment by mturley** [comment] 2019-09-25 20:03
It might come to that at the patternfly level, but I'm sure we're not the only product with this problem, I'd rather not duplicate the component all the way down here in v2v :)

**Comment by Hyperkid123** [comment] 2019-09-30 07:22
@himdel all of the deprecated props warnings unfortunately come from PF3. I was checking these components while I tried to upgrade to latest version of React.

**Comment by mturley** [comment] 2019-09-30 20:07
@Hyperkid123 if you have identified any other specific PF3 components besides Overlay which have this problem, would you mind leaving them in a comment on the pf-react issue? https://github.com/patternfly/patternfly-react/issues/3010

Part of the problem is that a bunch of the PF3 components are either thin wrappers for, or direct imports of, other libraries. So it's not as simple as searching the pf repos for those methods.

**Comment by Hyperkid123** [comment] 2019-10-01 07:00
I don't have the exact list but it should not take long to figure it out. I will check it.

**Comment by mturley** [comment] 2019-10-01 14:51
Sounds good. It looks like the `react-bootstrap` team is addressing this, and I think that will cover most of these instances, so I'll follow that effort and make sure patternfly-react pulls in the new version when it's available, and that we pull in that relevant patternfly-react release.

**Comment by mturley** [comment] 2019-10-30 22:32
react-bootstrap has released their fixes, the ball is now in patternfly court: https://github.com/patternfly/patternfly-react/pull/3249

**Comment by mturley** [comment] 2019-11-06 10:18
The fixes are now merged in patternfly-react, just waiting for the next patternfly release.

**Comment by himdel** [comment] 2019-12-04 15:45
Looks like this should be fixed in patternfly-react 2.39.8+ now.

And it is (except we also need to force react-bootstrap to 0.33 as react-ui-components still specifies 0.32),
but then the about modal breaks because of https://github.com/patternfly/patternfly-react/issues/3364 (https://github.com/react-bootstrap/react-bootstrap/issues/4872).

So, we can either get rid of the warnings and break dialogs, or wait :(, waiting.

(Tested with:

```diff
diff --git a/package.json b/package.json
index ab271a1db9..2b4447b37f 100644
--- a/package.json
+++ b/package.json
@@ -65,10 +65,11 @@
     "numeral": "~2.0.6",
     "patternfly": "~3.59.1",
     "patternfly-bootstrap-treeview": "~2.1.7",
-    "patternfly-react": "~2.39.1",
+    "patternfly-react": "~2.39.9",
     "prop-types": "^15.6.0",
     "proxy-polyfill": "^0.1.7",
     "react": "~16.9.0",
+    "react-bootstrap": "~0.33.0",
     "react-codemirror2": "^6.0.0",
     "react-dom": "~16.9.0",
     "react-redux": "^7.1.1",
```
)

Cc @martinpovolny

**Comment by mturley** [comment] 2019-12-13 22:41
@himdel I'm looking into this, but just a note that I was able to reproduce the issue without adding react-bootstrap as a dependency of manageiq-ui-classic directly, since that version is in the dependencies of the latest patternfly-react: https://github.com/patternfly/patternfly-react/blob/patternfly-react%402.39.9/packages/patternfly-3/patternfly-react/package.json#L33

**Comment by mturley** [comment] 2019-12-13 23:20
@himdel @martinpovolny I figured out the cause of this error, I'll draft a PR to fix it next week: https://github.com/patternfly/patternfly-react/issues/3364#issuecomment-565645973

**Comment by mturley** [comment] 2019-12-16 20:00
My fix for this was released in `patternfly-react@2.39.10` if you want to give that a try @himdel

**Comment by martinpovolny** [comment] 2019-12-17 14:26
Thanks, @mturley !

**Comment by himdel** [comment] 2019-12-17 14:57
:+1: Seems to work just fine, https://github.com/ManageIQ/manageiq-ui-classic/pull/6558

**Closed** 2019-12-17 21:03 UTC
Labels: UI, bug
