### ISSUE TITLE
[In Progress Cards] Migration should fail when denied due to lack of conversion host

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/manageiq-v2v#786] opened 2018-11-09 20:41 UTC
If a migration is kicked off where there is no conversion host configured in the target environment, the request will be denied.

We need to investigate what happens in this case and make sure that the In Progress Card goes away and the proper notification(s) are shown to the user

https://bugzilla.redhat.com/show_bug.cgi?id=1640816

Duplicate of #739

**Comment by michaelkro** [comment] 2018-11-13 14:32
Tried to investigate this on an appliance (cf-osp...).  And need some help setting up test scenario.  Here is what I observed

1. When creating a mapping, it appears that none of the target clusters have conversion hosts configured due to the warning icon
2. Created mapping
3. Created plan with the mapping and initiated migration
4. Migration request is approved, despite there being no configured conversion host
5. Drilling down into the active plan, I see that the task is polling in the `Acquiring Conversion Host` state

@fdupont-redhat, @bthurber

**Comment by bthurber** [comment] 2018-11-13 14:39
@michaelkro I believe on this build that is to be expected but going forward if a conversion host isn't available and the user decided to try a migration it should be denied and fail.

@fdupont-redhat let us know if that is your understanding based on our conversation last week.  It likely will require a code change to meet this behavior.

**Comment by fdupont-redhat** [comment] 2018-11-13 15:32
@michaelkro I confirm @bthurber's interpretation. In current build, it won't be denied. But with the following PRs merged, it should be in next one:

- https://github.com/ManageIQ/manageiq/pull/18135
- https://github.com/ManageIQ/manageiq-automation_engine/pull/263
- https://github.com/ManageIQ/manageiq-content/pull/455
- https://github.com/ManageIQ/manageiq-content/pull/471

So, the code change should only be on UI side, to reflect the fact that the request is denied. And the reason in available in request's message.

**Comment by michaelkro** [comment] 2018-11-13 16:42
Awesome, thanks @bthurber and @fdupont-redhat!

**Comment by michaelkro** [comment] 2018-11-13 23:42
@fdupont-redhat I'm testing out denied requests and wanted to double check some things with you :)

1. I created a mapping using a target cluster with no conversion host.  Then I created and ran a plan with that mapping
2. As expected, the request was never approved.
3. However, the request's attributes do not seem to get updated to indicate that it has been denied.

  ```
  [#<ServiceTemplateTransformationPlanRequest:0x00007f82d443f568
    id: 42000000000071,
    description: "Test",
    approval_state: "pending_approval",
    type: "ServiceTemplateTransformationPlanRequest",
    fulfilled_on: nil,
    requester_id: 42000000000001,
    requester_name: "Administrator",
    request_type: "transformation_plan",
    request_state: "pending",
    message: "VM Transformations - Request Created",
    status: "Ok",
    ...
    userid: "admin",
    source_id: 42000000000007,
    source_type: "ServiceTemplate",
    destination_id: nil,
    destination_type: nil,
    tenant_id: 42000000000001,
    service_order_id: 42000000000009,
    process: true,
    cancelation_status: nil>]
```
4. I also looked at the associated `MiqApproval`
```
// ServiceTemplateTransformationPlan.find('42000000000007').miq_requests.first.miq_approvals

[#<MiqApproval:0x00007f82d437e2f0
  id: 42000000000071,
  description: "Default Approval",
  state: "pending",
  reason: nil,
  miq_request_id: 42000000000071,
  stamped_on: nil,
  stamper_name: nil,
  stamper_id: nil,
  approver_id: nil,
  approver_type: nil,
  approver_name: nil,
  created_on: Tue, 13 Nov 2018 22:55:48 UTC +00:00,
  updated_on: Tue, 13 Nov 2018 22:55:48 UTC +00:00>]
```

I am wondering if I am looking in the wrong place?  Or maybe I am doing something incorrectly?

**Comment by mturley** [comment] 2018-11-16 20:23
Relevant mockup:

<img width="1079" alt="screenshot 2018-11-16 15 20 16" src="https://user-images.githubusercontent.com/811963/48645368-7ec41e80-e9b3-11e8-919e-2a8a43a23ede.png">

https://docs.google.com/presentation/d/1INIFpInmZ3oIjsxRw_SlTke6liGgvJLdasRD3uRVdzU/edit#slide=id.g45e2d2b245_0_6

**Comment by mturley** [comment] 2018-11-20 15:55
Marked this as a duplicate of #739, but since we've had comments in both issues, I'll leave both open for now.

**Closed** 2018-11-21 16:19 UTC
Labels: enhancement, hammer/yes, v1.1
