### ISSUE TITLE
Infra Mapping plan cannot be edit, after creation.

### ISSUE THREAD

**Issue by istein1** [ManageIQ/manageiq-v2v#250] opened 2018-04-25 12:37 UTC
Once the Mapping plan is created is not editable.

Version-Release:
master.20180417121918_2dd64f8 

Expected results:
It should be possible to edit Infra mapping plan.

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1571770

**Comment by vconzola** [comment] 2018-04-25 14:05
@istein1 Ability to edit/delete mappings and plans are on the roadmap for post-Summit sprints.

**Comment by istein1** [comment] 2018-04-26 09:05
Glad to hear, thanks or the update.

**Comment by vconzola** [comment] 2018-10-19 13:28
Duplicate of #607. Has been resolved by PR #620.

**Closed by vconzola** 2018-10-19 13:28 UTC
Labels: bz, enhancement, post-summit
