### ISSUE TITLE
Migration keep stuck for infinite in same state due to some failure

### ISSUE THREAD

**Issue by mnadeem92** [ManageIQ/manageiq-v2v#1097] opened 2020-01-27 06:04 UTC
Migration should went into failed state after some time period (time out) in case of failure and should not stuck for infinite time. The cancel option also not available for this kind of situations.

There is no option from GUI available for end user to stop/clean the stuck migration process. 
Please have a look at attached screenshots.

**Comment by mnadeem92** [comment] 2020-01-27 06:12
![failedissue2](https://user-images.githubusercontent.com/42543378/73153480-04844380-40fa-11ea-84bf-8738bfb72828.jpeg)
![failedissue1](https://user-images.githubusercontent.com/42543378/73153481-04844380-40fa-11ea-8ac8-9d82bce0d65c.jpeg)

**Comment by mnadeem92** [comment] 2020-01-27 06:13
It even won't allow to select the migration for cancelling it.

**Comment by mnadeem92** [comment] 2020-01-27 07:21
Issue reported for Version:  ManageIQ Jansa Version master.20200122225016_cb3eed5

**Comment by fdupont-redhat** [comment] 2020-01-27 08:21
Duplicate of #1098

**Closed by fdupont-redhat** 2020-01-27 08:21 UTC
